name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20.x'  # Specify Node.js version here
 

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKER_PAT }} | docker login --username muhammadshahincs --password-stdin

      - name: Build and run Docker image
        run: |
          docker build -t project_ci_cd_pipeline .
          docker run project_ci_cd_pipeline
